on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: bearer/bear-publishing
      - name: Scan
        uses: bearer/bearer-action@fix/account-for-base-image-changes
        with:
          version: 1.4.0
